# Changes here will be overwritten by Copier
_src_path: personal_templates/python
author_email: greysondn@gmail.com
author_name: J. "Dorian Greyson" L.
github_name: greysondn
package_name: appetite
project_name: APpetite
python_version: '3.12'
repo_push_url: https://github.com/greysondn/appetite.git
repo_url: https://github.com/greysondn/appetite
